// <auto-generated />
using System;
using DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ph_server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250424090905_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Entity.AccountDb", b =>
                {
                    b.Property<long>("account_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("account_id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("account_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("cash")
                        .HasColumnType("int");

                    b.Property<int>("current_exp")
                        .HasColumnType("int");

                    b.Property<int>("diamonds")
                        .HasColumnType("int");

                    b.Property<int>("gold")
                        .HasColumnType("int");

                    b.Property<int>("level_code")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("account_id");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("Entity.DbSet.ItemDb", b =>
                {
                    b.Property<long>("item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("item_id"));

                    b.Property<long>("account_id")
                        .HasColumnType("bigint");

                    b.Property<long?>("equipped_character_id")
                        .HasColumnType("bigint");

                    b.Property<int>("evolve_code")
                        .HasColumnType("int");

                    b.Property<int>("item_code")
                        .HasColumnType("int");

                    b.Property<int>("item_count")
                        .HasColumnType("int");

                    b.Property<int>("level_code")
                        .HasColumnType("int");

                    b.HasKey("item_id");

                    b.HasIndex("account_id");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("Entity.DbSet.ItemDb", b =>
                {
                    b.HasOne("Entity.AccountDb", null)
                        .WithMany("items")
                        .HasForeignKey("account_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entity.AccountDb", b =>
                {
                    b.Navigation("items");
                });
#pragma warning restore 612, 618
        }
    }
}
